apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-config
data:
  PEERS: |
    10.10.0.10:8000,10.10.0.11:8000,10.10.0.12:8000,10.10.0.13:8000,10.10.0.14:8000,
    10.20.0.10:8000,10.20.0.11:8000,10.20.0.12:8000,10.20.0.13:8000,10.20.0.14:8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iot-node
spec:
  serviceName: "iot"
  replicas: 5
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: node
        image: us-central1-docker.pkg.dev/{{PROJECT_ID}}/gcp-docker-repo/decentral:latest
        ports:
        - containerPort: 8000
        env:
        - name: PEERS
          valueFrom:
            configMapKeyRef:
              name: peer-config
              key: PEERS
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"