# iot-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: iot-node-1
  labels:
    app: iot
spec:
  containers:
  - name: node
    image: us-central1-docker.pkg.dev/{{PROJECTID}}/gcp-docker-repo/decentral:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: divanalysis-service
# spec:
#   selector:
#     app: divanalysis
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5050
#   type: LoadBalancer
#   loadBalancerIP: 104.155.141.5

