apiVersion: v1
kind: Service
metadata:
  name: iot
  labels:
    app: iot
spec:
  clusterIP: None
  selector:
    app: iot
  ports:
  - port: 8000
    name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iot-node
spec:
  serviceName: "iot"
  replicas: 3
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: node
        image: us-central1-docker.pkg.dev/{{PROJECTID}}/gcp-docker-repo/decentral:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PEERS
          value: "iot-node-0.iot:8000,iot-node-1.iot:8000,iot-node-2.iot:8000"
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
