# iot-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: iot-node-1
  labels:
    app: iot
spec:
  containers:
  - name: node
    image: your-registry/iot-node:latest
    ports:
    - containerPort: 8000

